### PR TITLE
Update for rust 1.16.0+

### PR DESCRIPTION
**Pull request by jedisct1**
This updates the shoop code for current versions of Rust & dependencies.

### CODE REVIEW

**Comment by mcginty** [comment]
@jedisct1 Hey thanks so much for the PR! Will check it out tonight.

**Comment by jedisct1** [comment]
I initially forgot to update the tests, sorry -- Done.

**Comment by jedisct1** [comment]
Ping?

**Comment by mcginty** [comment]
Hey @jedisct1, apologies for the lag (life happened). I just checked it out and tested it - looks good.

Thanks again for the PR!

**Pull request merged**
